# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/dratini/Documents/GitHub/EE382N-AdvanceMCU/project_1/project_1.srcs/sources_1/bd/BlockRam/ip/BlockRam_axi_gpio_0_0/BlockRam_axi_gpio_0_0.xci
# IP: The module: 'BlockRam_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/dratini/Documents/GitHub/EE382N-AdvanceMCU/project_1/project_1.srcs/sources_1/bd/BlockRam/ip/BlockRam_axi_gpio_0_0/BlockRam_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'BlockRam_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/dratini/Documents/GitHub/EE382N-AdvanceMCU/project_1/project_1.srcs/sources_1/bd/BlockRam/ip/BlockRam_axi_gpio_0_0/BlockRam_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'BlockRam_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/dratini/Documents/GitHub/EE382N-AdvanceMCU/project_1/project_1.srcs/sources_1/bd/BlockRam/ip/BlockRam_axi_gpio_0_0/BlockRam_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'BlockRam_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/dratini/Documents/GitHub/EE382N-AdvanceMCU/project_1/project_1.srcs/sources_1/bd/BlockRam/ip/BlockRam_axi_gpio_0_0/BlockRam_axi_gpio_0_0.xci
# IP: The module: 'BlockRam_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/dratini/Documents/GitHub/EE382N-AdvanceMCU/project_1/project_1.srcs/sources_1/bd/BlockRam/ip/BlockRam_axi_gpio_0_0/BlockRam_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'BlockRam_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/dratini/Documents/GitHub/EE382N-AdvanceMCU/project_1/project_1.srcs/sources_1/bd/BlockRam/ip/BlockRam_axi_gpio_0_0/BlockRam_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'BlockRam_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/dratini/Documents/GitHub/EE382N-AdvanceMCU/project_1/project_1.srcs/sources_1/bd/BlockRam/ip/BlockRam_axi_gpio_0_0/BlockRam_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'BlockRam_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
