# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/BlockRam/BlockRam.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BlockRam || ORIG_REF_NAME==BlockRam} -quiet] -quiet

# IP: bd/BlockRam/ip/BlockRam_processing_system7_0_0/BlockRam_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BlockRam_processing_system7_0_0 || ORIG_REF_NAME==BlockRam_processing_system7_0_0} -quiet] -quiet

# IP: bd/BlockRam/ip/BlockRam_proc_sys_reset_0_0/BlockRam_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BlockRam_proc_sys_reset_0_0 || ORIG_REF_NAME==BlockRam_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/BlockRam/ip/BlockRam_axi_interconnect_0_0/BlockRam_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BlockRam_axi_interconnect_0_0 || ORIG_REF_NAME==BlockRam_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/BlockRam/ip/BlockRam_axi_bram_ctrl_0_1/BlockRam_axi_bram_ctrl_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BlockRam_axi_bram_ctrl_0_1 || ORIG_REF_NAME==BlockRam_axi_bram_ctrl_0_1} -quiet] -quiet

# IP: bd/BlockRam/ip/BlockRam_axi_bram_ctrl_0_2/BlockRam_axi_bram_ctrl_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BlockRam_axi_bram_ctrl_0_2 || ORIG_REF_NAME==BlockRam_axi_bram_ctrl_0_2} -quiet] -quiet

# IP: bd/BlockRam/ip/BlockRam_axi_gpio_0_0/BlockRam_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BlockRam_axi_gpio_0_0 || ORIG_REF_NAME==BlockRam_axi_gpio_0_0} -quiet] -quiet

# IP: bd/BlockRam/ip/BlockRam_xbar_0/BlockRam_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BlockRam_xbar_0 || ORIG_REF_NAME==BlockRam_xbar_0} -quiet] -quiet

# IP: bd/BlockRam/ip/BlockRam_LFSR_0_1/BlockRam_LFSR_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BlockRam_LFSR_0_1 || ORIG_REF_NAME==BlockRam_LFSR_0_1} -quiet] -quiet

# IP: bd/BlockRam/ip/BlockRam_blk_mem_gen_0_1/BlockRam_blk_mem_gen_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BlockRam_blk_mem_gen_0_1 || ORIG_REF_NAME==BlockRam_blk_mem_gen_0_1} -quiet] -quiet

# IP: bd/BlockRam/ip/BlockRam_auto_pc_1/BlockRam_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BlockRam_auto_pc_1 || ORIG_REF_NAME==BlockRam_auto_pc_1} -quiet] -quiet

# IP: bd/BlockRam/ip/BlockRam_auto_pc_0/BlockRam_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BlockRam_auto_pc_0 || ORIG_REF_NAME==BlockRam_auto_pc_0} -quiet] -quiet

# IP: bd/BlockRam/ip/BlockRam_auto_pc_2/BlockRam_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BlockRam_auto_pc_2 || ORIG_REF_NAME==BlockRam_auto_pc_2} -quiet] -quiet

# XDC: bd/BlockRam/BlockRam_ooc.xdc
